// Code generated by gen-meta/main.go; DO NOT EDIT.
package main

import (
	"context"
	"fmt"
	"io/ioutil"
	"net/http"
)

var _ = fmt.Print

const Author = "Shintaro Kaneko"
const Homepage = "https://github.com/kaneshin/go-generate-sample#readme"

func HTML(ctx context.Context) ([]byte, error) {
	resp, err := http.Get(Homepage)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	body, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	return body, nil
}
